services:
  app:
    container_name: manovspace
    networks:
      - manovspace-network
    build:
      context: services/app
      dockerfile: Dockerfile.dev
    env_file: .env
    command: mix phx.server
    environment:
      MIX_ENV: dev
      FILESYSTEM_FSINOTIFY_EXECUTABLE_FILE: /usr/bin/inotifywait
    ports:
      - "${MANOVSPACE_PORT}:${MANOVSPACE_PORT}"
      - "${TRACKER_PORT}:${TRACKER_PORT}"
    depends_on:
      - db_tracker

  db_tracker:
    container_name: db_tracker
    networks:
      - manovspace-network
    image: postgres:12-alpine
    env_file: .env
    environment:
      POSTGRES_DB: ${TRACKER_DB}
      POSTGRES_USER: ${USER_TRACKER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_TRACKER_DB}
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "${TRACKER_PORT_DB}:${TRACKER_PORT_DB}"

networks:
  manovspace-network:
    driver: bridge
